name: Test & Build

on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x

    - name: Install
      run: npm install

    - name: Test
      run: npm test


# vi: sw=2 sts=2
